stages:
  - test
  - deploy

test:8_1:
  before_script:
    - bash .ci-cd/build.sh > /dev/null
  image: php:8.1
  stage: test
  variables:
    SRC_DIR: src
  script:
    - vendor/bin/phpunit -v --coverage-text --coverage-html=coverage --colors=never
  artifacts:
    paths:
      - coverage

deploy:
  stage: deploy

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get      install openssh-client -y)'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - which rsync || ( apt-get update -y && apt-get install rsync -y )

  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - rsync -rvzD -e "ssh -o PubkeyAuthentication=no StrictHostKeyChecking=no" --exclude='.git/' --exclude='.gitlab-ci.yml' ./ root@87.106.236.166:/var/www/zoom-chat-to-srt/
    - ssh -o PubkeyAuthentication=no StrictHostKeyChecking=no root@87.106.236.166 "composer install --working-dir=/var/www/zoom-chat-to-srt/"
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - test:8_1
  script:
    - mv coverage public
  artifacts:
    paths:
      - public
    expire_in: 30 days
